Step 0 Importing data and libraries

In [32]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pylab as plt
plt.style.use('ggplot')
pd.set_option('display.max_columns', 200)

In [12]:
df=pd.read_csv("lci-mar26qtr-tables.csv")

df.head(5)

In [27]:
df.head()

,Series_reference,Period,Data_value,STATUS,UNITS,MAGNTUDE,Subject,Group,Series_title_1,Series_title_2,Series_title_3,Series_title_4,Series_title_5
0,LCIQ.SD53Z9,1992.12,610.484966,FINAL,index,0,Labour Cost Index - LCI,"All Sectors Combined, All Salary and Wage Rate...",All Sectors Combined,All Salary and Wage Rates,All Industries/Occupations Combined,NaN,NaN
1,LCIQ.SD53Z9,1993.03,612.316421,FINAL,index,0,Labour Cost Index - LCI,"All Sectors Combined, All Salary and Wage Rate...",All Sectors Combined,All Salary and Wage Rates,All Industries/Occupations Combined,NaN,NaN
2,LCIQ.SD53Z9,1993.06,614.147876,FINAL,index,0,Labour Cost Index - LCI,"All Sectors Combined, All Salary and Wage Rate...",All Sectors Combined,All Salary and Wage Rates,All Industries/Occupations Combined,NaN,NaN
3,LCIQ.SD53Z9,1993.09,615.368846,FINAL,index,0,Labour Cost Index - LCI,"All Sectors Combined, All Salary and Wage Rate...",All Sectors Combined,All Salary and Wage Rates,All Industries/Occupations Combined,NaN,NaN
4,LCIQ.SD53Z9,1993.12,616.589815,FINAL,index,0,Labour Cost Index - LCI,"All Sectors Combined, All Salary and Wage Rate...",All Sectors Combined,All Salary and Wage Rates,All Industries/Occupations Combined,NaN,NaN

In [15]:
df.shape

(32546, 13)

In [18]:
df.columns

Index(['Series_reference', 'Period', 'Data_value', 'STATUS', 'UNITS',
       'MAGNTUDE', 'Subject', 'Group', 'Series_title_1', 'Series_title_2',
       'Series_title_3', 'Series_title_4', 'Series_title_5'],
      dtype='object')

In [19]:
df.dtypes

Series_reference     object
Period              float64
Data_value          float64
STATUS               object
UNITS                object
MAGNTUDE              int64
Subject              object
Group                object
Series_title_1       object
Series_title_2       object
Series_title_3       object
Series_title_4       object
Series_title_5       object
dtype: object

In [20]:
df.describe()

             Period    Data_value  MAGNTUDE
count  32546.000000  32534.000000   32546.0
mean    2014.593977    861.137081       0.0
std        7.705778    519.959790       0.0
min     1989.060000      0.000000       0.0
25%     2010.120000     59.000000       0.0
50%     2015.120000   1078.000000       0.0
75%     2021.030000   1211.000000       0.0
max     2026.030000   1819.000000       0.0

In [33]:
df.drop(["Series_title_4","Series_title_5"], axis=1)
##dropping single columns

,Series_reference,Period,Data_value,STATUS,UNITS,MAGNTUDE,Subject,Group,Series_title_1,Series_title_2,Series_title_3
0,LCIQ.SD53Z9,1992.12,610.484966,FINAL,index,0,Labour Cost Index - LCI,"All Sectors Combined, All Salary and Wage Rate...",All Sectors Combined,All Salary and Wage Rates,All Industries/Occupations Combined
1,LCIQ.SD53Z9,1993.03,612.316421,FINAL,index,0,Labour Cost Index - LCI,"All Sectors Combined, All Salary and Wage Rate...",All Sectors Combined,All Salary and Wage Rates,All Industries/Occupations Combined
2,LCIQ.SD53Z9,1993.06,614.147876,FINAL,index,0,Labour Cost Index - LCI,"All Sectors Combined, All Salary and Wage Rate...",All Sectors Combined,All Salary and Wage Rates,All Industries/Occupations Combined
3,LCIQ.SD53Z9,1993.09,615.368846,FINAL,index,0,Labour Cost Index - LCI,"All Sectors Combined, All Salary and Wage Rate...",All Sectors Combined,All Salary and Wage Rates,All Industries/Occupations Combined
4,LCIQ.SD53Z9,1993.12,616.589815,FINAL,index,0,Labour Cost Index - LCI,"All Sectors Combined, All Salary and Wage Rate...",All Sectors Combined,All Salary and Wage Rates,All Industries/Occupations Combined
...,...,...,...,...,...,...,...,...,...,...,...
32541,LCIQ.SX529A,2025.03,51.000000,FINAL,Percent,0,Labour Cost Index - LCI,Distribution of Movement,All Sectors Combined,Overtime Wage Rates,Total Increasing for the Year
32542,LCIQ.SX529A,2025.06,57.000000,FINAL,Percent,0,Labour Cost Index - LCI,Distribution of Movement,All Sectors Combined,Overtime Wage Rates,Total Increasing for the Year
32543,LCIQ.SX529A,2025.09,56.000000,FINAL,Percent,0,Labour Cost Index - LCI,Distribution of Movement,All Sectors Combined,Overtime Wage Rates,Total Increasing for the Year
32544,LCIQ.SX529A,2025.12,53.000000,FINAL,Percent,0,Labour Cost Index - LCI,Distribution of Movement,All Sectors Combined,Overtime Wage Rates,Total Increasing for the Year
32545,LCIQ.SX529A,2026.03,54.000000,FINAL,Percent,0,Labour Cost Index - LCI,Distribution of Movement,All Sectors Combined,Overtime Wage Rates,Total Increasing for the Year

In [39]:
##rename our columns

In [ ]:
df.rename(columns={'Series_title_1':'Sectors','Series_title_2':'Wage'})
df.drop(['Series_title_4','Series_title_5'],axis=1)

,Series_reference,Period,Data_value,STATUS,UNITS,MAGNTUDE,Subject,Group,Series_title_1,Series_title_2,Series_title_3
0,LCIQ.SD53Z9,1992.12,610.484966,FINAL,index,0,Labour Cost Index - LCI,"All Sectors Combined, All Salary and Wage Rate...",All Sectors Combined,All Salary and Wage Rates,All Industries/Occupations Combined
1,LCIQ.SD53Z9,1993.03,612.316421,FINAL,index,0,Labour Cost Index - LCI,"All Sectors Combined, All Salary and Wage Rate...",All Sectors Combined,All Salary and Wage Rates,All Industries/Occupations Combined
2,LCIQ.SD53Z9,1993.06,614.147876,FINAL,index,0,Labour Cost Index - LCI,"All Sectors Combined, All Salary and Wage Rate...",All Sectors Combined,All Salary and Wage Rates,All Industries/Occupations Combined
3,LCIQ.SD53Z9,1993.09,615.368846,FINAL,index,0,Labour Cost Index - LCI,"All Sectors Combined, All Salary and Wage Rate...",All Sectors Combined,All Salary and Wage Rates,All Industries/Occupations Combined
4,LCIQ.SD53Z9,1993.12,616.589815,FINAL,index,0,Labour Cost Index - LCI,"All Sectors Combined, All Salary and Wage Rate...",All Sectors Combined,All Salary and Wage Rates,All Industries/Occupations Combined

In [59]:
df.head()

,Series_reference,Period,Data_value,STATUS,UNITS,MAGNTUDE,Subject,Group,Sectors,Wage,Series_title_3
0,LCIQ.SD53Z9,1992.12,610.484966,FINAL,index,0,Labour Cost Index - LCI,"All Sectors Combined, All Salary and Wage Rate...",All Sectors Combined,All Salary and Wage Rates,All Industries/Occupations Combined
1,LCIQ.SD53Z9,1993.03,612.316421,FINAL,index,0,Labour Cost Index - LCI,"All Sectors Combined, All Salary and Wage Rate...",All Sectors Combined,All Salary and Wage Rates,All Industries/Occupations Combined
2,LCIQ.SD53Z9,1993.06,614.147876,FINAL,index,0,Labour Cost Index - LCI,"All Sectors Combined, All Salary and Wage Rate...",All Sectors Combined,All Salary and Wage Rates,All Industries/Occupations Combined
3,LCIQ.SD53Z9,1993.09,615.368846,FINAL,index,0,Labour Cost Index - LCI,"All Sectors Combined, All Salary and Wage Rate...",All Sectors Combined,All Salary and Wage Rates,All Industries/Occupations Combined
4,LCIQ.SD53Z9,1993.12,616.589815,FINAL,index,0,Labour Cost Index - LCI,"All Sectors Combined, All Salary and Wage Rate...",All Sectors Combined,All Salary and Wage Rates,All Industries/Occupations Combined

In [65]:
df.loc[df.duplicated()]
#to check for duploicated values

Empty DataFrame
Columns: [Series_reference, Period, Data_value, STATUS, UNITS, MAGNTUDE, Subject, Group, Sectors, Wage, Series_title_3]
Index: []

In [64]:
df.duplicated(subset=['Series_reference'])

0        False
1         True
2         True
3         True
4         True
         ...
32541     True
32542     True
32543     True
32544     True
32545     True
Length: 32546, dtype: bool

In [68]:
df.loc[df.duplicated(subset=['Series_reference'])].head()
##to display first 5

,Series_reference,Period,Data_value,STATUS,UNITS,MAGNTUDE,Subject,Group,Sectors,Wage,Series_title_3
1,LCIQ.SD53Z9,1993.03,612.316421,FINAL,index,0,Labour Cost Index - LCI,"All Sectors Combined, All Salary and Wage Rate...",All Sectors Combined,All Salary and Wage Rates,All Industries/Occupations Combined
2,LCIQ.SD53Z9,1993.06,614.147876,FINAL,index,0,Labour Cost Index - LCI,"All Sectors Combined, All Salary and Wage Rate...",All Sectors Combined,All Salary and Wage Rates,All Industries/Occupations Combined
3,LCIQ.SD53Z9,1993.09,615.368846,FINAL,index,0,Labour Cost Index - LCI,"All Sectors Combined, All Salary and Wage Rate...",All Sectors Combined,All Salary and Wage Rates,All Industries/Occupations Combined
4,LCIQ.SD53Z9,1993.12,616.589815,FINAL,index,0,Labour Cost Index - LCI,"All Sectors Combined, All Salary and Wage Rate...",All Sectors Combined,All Salary and Wage Rates,All Industries/Occupations Combined
5,LCIQ.SD53Z9,1994.03,618.421270,FINAL,index,0,Labour Cost Index - LCI,"All Sectors Combined, All Salary and Wage Rate...",All Sectors Combined,All Salary and Wage Rates,All Industries/Occupations Combined